ALTER TABLE requests
    ADD COLUMN response_id TEXT,
    ADD COLUMN upstream_request_id TEXT,
    ADD COLUMN response_model TEXT,
    ADD COLUMN response_status TEXT,
    ADD COLUMN service_tier TEXT,
    ADD COLUMN input_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN cached_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN output_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN total_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN web_search_requests BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_input_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_input_image_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_input_text_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_output_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_output_image_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_output_text_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN image_gen_total_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN response_error JSONB,
    ADD COLUMN incomplete_details JSONB,
    ADD COLUMN codex_headers JSONB;
